### ISSUE TITLE
[BUG] Skillcloaks and backpacks

### ISSUE THREAD

**Issue by Wolris** [Mindoth/skillcloaks#1]
Using the mod with Sophisticated backpacks results in neither being able to use Curios slots

Version of Minecraft: 1.20.1
 
Version of Mod: 1.2.1

Client or Server: Client

**Comment by Wolris** [comment]
Update: Reverting to 1.1.9 resolves this

**Comment by Mindoth** [comment]
Thanks for bringing this to attention. I have found the problem and fixed it.
