### ISSUE TITLE
[COMPAT ISSUE] Skillcloaks + CustomizableElytras

### ISSUE THREAD

**Issue by michaelukz** [Mindoth/skillcloaks#2]
Version of Minecraft: 1.20.1

 

Version of Mod: skillcloaks-1.20.1-1.1.9

 

Client or Server: Client

 

More information: There seems to be a compatibility between CustomizableElytra and Skillcloaks.

When trying to equip a skillcloak with a custom elytra equipped it crashes the game, and attempting to rejoin will instantly crash again making a single player world unplayable without NBTEdit.

Attached is the crash report.
[crash-2023-10-29_01.35.47-client.txt](https://github.com/Mindoth/skillcloaks/files/13230394/crash-2023-10-29_01.35.47-client.txt)

**Comment by michaelukz** [comment]
Having spoken with Hidoni of CustomizableElytra mod, they have made a fix on their version, but as he didn't specify the issue, I will leave this one open on the chance it's also an issue on this mod's side as well.

**Comment by Mindoth** [comment]
I took a glance on their repo and the way I see it something was conflicting with getting the player's elytra texture. Yeah... Mixins are a bit finicky. If they found a way to fix it on their side then great. I'll close this for now.
